18.5-rails-review/done-kit/config/routes.rb
Rails.application.routes.draw do
  resources :dogs, only: [:show, :index]
  resources :employees
  # welcome page
  get '/', to: 'welcome#index', as: 'start'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

18.5-rails-review/done-kit/app/models/dog.rb
class Dog < ApplicationRecord
    has_many :employees, :dependent => :delete_all

    validates :name, presence: true

    def employee_count
        self.employees.count
    end
    
end

18.5-rails-review/done-kit/app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :dog

    validates :first_name, presence: true, uniqueness: true
    validates :last_name, presence: true, uniqueness: true
    validates :alias, presence: true, uniqueness: true
    validates :title, presence: true, uniqueness: true
  
    def name
      first_name + " " + last_name
    end
    
end

18.5-rails-review/done-kit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

18.5-rails-review/done-kit/app/controllers/dogs_controller.rb
class DogsController < ApplicationController

    def index
      @dogs = Dog.all
    end
  
    def show
      @dog = Dog.find(params[:id])
    end
  
  end

18.5-rails-review/done-kit/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    before_action :get_employee, only: [:show, :edit, :destroy]
  
    def index
      @employees = Employee.all
    end
  
    def new
      @employee = Employee.new
      @errors = flash[:errors]
    end
  
    def create
      @employee = Employee.create(employee_params)
      if @employee.save
        flash[:success] = "Good job filling out the form!"
        redirect_to @employee
      else
        flash[:errors] = @employee.errors.full_messages
        redirect_to employee_new_path
      end
    end
   
    def update
      if get_employee.update(employee_params)
        redirect_to @employee
      else
        redirect_to employee_edit_path
      end
    end
  
    def destroy
        @employee.destroy
        redirect_to employees_path
    end
  
  private
  
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :alias, :title, :office, :img_url, :dog_id)
    end
  
    def get_employee
      @employee = Employee.find(params[:id])
    end
  
  end

18.5-rails-review/done-kit/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index
    end

end

18.5-rails-review/done-kit/app/helpers/dogs_helper.rb
module DogsHelper
end

18.5-rails-review/done-kit/app/helpers/employees_helper.rb
module EmployeesHelper
end

18.5-rails-review/done-kit/app/views/dogs/_footer.html.erb
<%= link_to "Back to homepage", start_path %>

18.5-rails-review/done-kit/app/views/dogs/_header.html.erb
<ol>
  <li>  <%= link_to "Employees", employees_path %> </li>
  <li>  <%= link_to "Dogs", dogs_path %> </li>
</ol>
<hr>

18.5-rails-review/done-kit/app/views/dogs/index.html.erb
<%= render 'header' %>
<h1>All Dogs</h1>

  <% if params[:sort] == "true"%>
  <%= link_to "Sort by Number of Owners ⬇", "#{dogs_path}?sort=false" %>
  <% @dogs = @dogs.sort_by{|dog| dog.employee_count} %>
  <% else %>
  <%= link_to "Sort by Number of Owners ⬆", "#{dogs_path}?sort=true" %>
  <% @dogs = @dogs.sort_by{|dog| dog.employee_count}.reverse %>
  <% end %>

<% @dogs.each do |dog| %>
<ul><li>
  <%= link_to dog.name, dog %> </li>
</ul>
<% end %>

<%= render 'footer' %>

18.5-rails-review/done-kit/app/views/dogs/show.html.erb
<%= render 'header' %>

<h1><%=@dog.name%></h1>
<br>

<p><strong> Name: </strong><%=@dog.name%></p>
<p><strong> Breed:</strong> <%=@dog.breed%></p>
<p><strong> Belongs to: </strong> <ul><% @dog.employees.each do |employee| %></p>
<li> <%= link_to employee.name, employee %></li>
<% end %>
</ul>

<%= render 'footer' %>

18.5-rails-review/done-kit/app/views/welcome/index.html.erb
<h1>Welcome to the Dunder Mifflin Pet Show!</h1>
<br>
<%= button_to  "See our dogs", dogs_path, method: "get"%> <br>
<%= button_to  "Meet their owners", employees_path, method: "get"%><br>