15-intro-to-rails/rails-universe/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/universes", to: "universes#index", as: "universes"
  get "/universes/:id", to: "universes#show", as: "universe"

  get "/universes/:id/destroy_its_planets", to: "universes#blow_em_up", as: "blow_em_up"

  get "/beef", to: "whatever#hmm"

end

15-intro-to-rails/rails-universe/app/models/universe.rb
class Universe < ApplicationRecord
end

15-intro-to-rails/rails-universe/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

15-intro-to-rails/rails-universe/app/controllers/universes_controller.rb
class UniversesController < ApplicationController

  # index
  # get '/universes' do
  #   # model
  #   @universes = Universe.all
    
  #   # response
  #   erb :"universes/index"
  # end

  def index
    # model
    @universes = Universe.all

    byebug
    
    # response
    render :index
  end

  def show
    # model 
    @universe = Universe.find_by(id: params[:id])

    # response
    render :show
  end

end

15-intro-to-rails/rails-universe/app/controllers/whatever_controller.rb
class WhateverController < ApplicationController

  def nope

  end

end

15-intro-to-rails/rails-universe/app/views/universes/index.erb
<h1>Here are all the Universes!</h1>

<% @universes.each do |universe| %>
  <p>
    <%= link_to universe.name, "/universes/#{universe.id}" %>
    <%= link_to universe.name, universe_path(universe.id) %>
    <%= link_to universe.name, universe %>
  </p>
<% end %>

15-intro-to-rails/rails-universe/app/views/universes/show.erb
<h1>This is the Show page for <%= @universe.name %></h1>

<%# link_to(@universe.name, "/universes/#{@universe.id}/edit") %>

<a href="/universes/<%= @universe.id %>/edit">
  Edit <%= @universe.name %>
</a>

<p>
  Size: <%= @universe.planet_count %>
</p>